export const isErrnoException = (e) => e instanceof Error;
